#!/usr/bin/env python3
"""Build a consolidated report from an OpenBench run matrix manifest."""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


@dataclass
class ManifestEntry:
    dataset: str
    profile: str
    run_name: str
    status: str


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build matrix summary from OpenBench run manifest.")
    parser.add_argument("--manifest", type=Path, required=True, help="TSV manifest generated by run script.")
    parser.add_argument("--runs-root", type=Path, required=True, help="OpenBench runs root directory.")
    parser.add_argument("--output-json", type=Path, required=True, help="Output JSON report path.")
    parser.add_argument("--output-csv", type=Path, required=True, help="Output CSV report path.")
    return parser.parse_args()


def _read_manifest(path: Path) -> list[ManifestEntry]:
    entries: list[ManifestEntry] = []
    lines = [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if not lines:
        return entries
    for idx, line in enumerate(lines):
        if idx == 0 and line.startswith("dataset\tprofile\trun_name\tstatus"):
            continue
        parts = line.split("\t")
        if len(parts) != 4:
            continue
        entries.append(ManifestEntry(dataset=parts[0], profile=parts[1], run_name=parts[2], status=parts[3]))
    return entries


def _safe_float(value: Any) -> float | None:
    try:
        return float(value)
    except Exception:
        return None


def _collect_row(entry: ManifestEntry, runs_root: Path) -> dict[str, Any]:
    row: dict[str, Any] = {
        "dataset": entry.dataset,
        "profile": entry.profile,
        "run_name": entry.run_name,
        "status": entry.status,
        "wer": None,
        "rtf": None,
        "speed_x": None,
        "num_samples": None,
        "total_audio_sec": None,
        "total_prediction_sec": None,
        "run_dir": str(runs_root / entry.run_name),
        "summary_path": str(runs_root / entry.run_name / "custom-openbench-summary.json"),
    }

    if entry.status != "ok":
        return row

    summary_path = runs_root / entry.run_name / "custom-openbench-summary.json"
    if not summary_path.exists():
        row["status"] = "missing_summary"
        return row

    try:
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
    except Exception:
        row["status"] = "invalid_summary"
        return row

    wer = summary.get("global_metrics", {}).get("wer", {}).get("global_result")
    row["wer"] = _safe_float(wer)
    row["rtf"] = _safe_float(summary.get("rtf"))
    row["speed_x"] = _safe_float(summary.get("speed_x"))
    row["num_samples"] = summary.get("num_samples")
    row["total_audio_sec"] = _safe_float(summary.get("total_audio_sec"))
    row["total_prediction_sec"] = _safe_float(summary.get("total_prediction_sec"))
    return row


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fieldnames = [
        "dataset",
        "profile",
        "run_name",
        "status",
        "wer",
        "rtf",
        "speed_x",
        "num_samples",
        "total_audio_sec",
        "total_prediction_sec",
        "run_dir",
        "summary_path",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    args = _parse_args()

    entries = _read_manifest(args.manifest)
    rows = [_collect_row(entry, args.runs_root) for entry in entries]
    failures = [row for row in rows if row.get("status") != "ok"]

    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "manifest_path": str(args.manifest),
        "runs_root": str(args.runs_root),
        "total_runs": len(rows),
        "ok_runs": len(rows) - len(failures),
        "failed_runs": len(failures),
        "rows": rows,
    }

    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(json.dumps(report, indent=2), encoding="utf-8")
    _write_csv(args.output_csv, rows)

    print(json.dumps({"output_json": str(args.output_json), "output_csv": str(args.output_csv)}, indent=2))


if __name__ == "__main__":
    main()

